apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bioorchestrator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/nkz-os/gitops-config
    targetRevision: HEAD
    path: overlays/modules/bioorchestrator
    directory:
      exclude: '{bioorchestrator-sealed-secret.yaml,bioorchestrator-ingress.yaml}'
  destination:
    server: https://kubernetes.default.svc
    namespace: nekazari
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
