apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gis-routing
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/nkz-os/nkz-module-gis-routing
    targetRevision: HEAD
    path: k8s
    directory:
      recurse: true
      exclude: '{registration.sql}'
  destination:
    server: https://kubernetes.default.svc
    namespace: nekazari
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
