import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { join, relative, posix } from 'node:path';

export type EntryStrategy = 'modern' | 'legacy';

/**
 * Detect which entry strategy a module uses.
 *
 * - "modern": src/Module.tsx with `export default defineModule(...)`.
 *   The builder will codegen moduleEntry.gen.ts.
 * - "legacy": src/moduleEntry.ts written by hand.
 *   The builder uses it as-is.
 *
 * If both files exist, modern wins (the legacy file is ignored).
 */
export function detectEntryStrategy(projectRoot: string): EntryStrategy {
  const hasModern = existsSync(join(projectRoot, 'src/Module.tsx'));
  const hasLegacy = existsSync(join(projectRoot, 'src/moduleEntry.ts'));

  if (hasModern) return 'modern';
  if (hasLegacy) return 'legacy';

  throw new Error(
    `[@nekazari/module-builder] Neither src/Module.tsx (modern) nor src/moduleEntry.ts (legacy) found in ${projectRoot}. ` +
      `Create one of them. The modern form is preferred.`,
  );
}

/**
 * Generate `node_modules/.nkz/moduleEntry.gen.ts` from `src/Module.tsx`.
 * Returns the absolute path of the generated file (used as Vite's input).
 */
export function generateModuleEntry(projectRoot: string): string {
  const outDir = join(projectRoot, 'node_modules/.nkz');
  const outFile = join(outDir, 'moduleEntry.gen.ts');

  mkdirSync(outDir, { recursive: true });

  // Resolve the import path relative to the output file
  const moduleAbs = join(projectRoot, 'src/Module');
  const relPath = posix.normalize(relative(outDir, moduleAbs)).replace(/\\/g, '/');
  const importSpec = relPath.startsWith('.') ? relPath : `./${relPath}`;

  const sourceRel = relative(projectRoot, join(projectRoot, 'src/Module.tsx'));

  // Built as concatenation to keep the inner template literal in the generated
  // file readable. The generated file uses its own backtick string for the
  // error message — we cannot nest backticks naively.
  const code =
    `/* eslint-disable */\n` +
    `// =============================================================================\n` +
    `// GENERATED by @nekazari/module-builder — do not edit.\n` +
    `// Source: ${sourceRel}\n` +
    `// Run \`nkz why moduleEntry.gen.ts\` to see how this file was derived.\n` +
    `// =============================================================================\n` +
    `import moduleConfig from '${importSpec}';\n` +
    `import { toNKZRegistration } from '@nekazari/module-kit';\n` +
    `\n` +
    `declare global {\n` +
    `  interface Window {\n` +
    `    __NKZ__?: { register: (registration: ReturnType<typeof toNKZRegistration>) => void };\n` +
    `  }\n` +
    `}\n` +
    `\n` +
    `if (typeof window !== 'undefined' && window.__NKZ__) {\n` +
    `  window.__NKZ__.register(toNKZRegistration(moduleConfig));\n` +
    `} else if (typeof window !== 'undefined') {\n` +
    "  console.error(`[${moduleConfig.id}] window.__NKZ__ not found. Is this bundle loaded inside an NKZ host?`);\n" +
    `}\n` +
    `\n` +
    `export default moduleConfig;\n`;

  writeFileSync(outFile, code, 'utf-8');
  return outFile;
}

import type { ModuleDefinition } from '@nekazari/module-kit';

/**
 * Strip runtime-only fields from a ModuleDefinition and return a plain JSON
 * object suitable for writing as `dist/manifest.json`.
 *
 * The manifest is what the host reads from MinIO when discovering a module —
 * it must be pure data (no functions, no React components).
 */
export function generateManifest(def: ModuleDefinition): Record<string, unknown> {
  const manifest: Record<string, unknown> = {
    id: def.id,
    displayName: def.displayName,
    version: def.version,
    hostApiVersion: def.hostApiVersion,
    description: def.description,
    accent: def.accent,
    icon: def.icon,
    route: def.route,
    navigation: def.navigation,
    api: def.api,
    requiredRoles: def.requiredRoles,
    requiredPlan: def.requiredPlan,
    data: def.data,
  };

  if (def.slots) {
    const slotsOut: Record<string, Array<Record<string, unknown>>> = {};
    for (const [slotType, entries] of Object.entries(def.slots)) {
      slotsOut[slotType] = (entries as Array<Record<string, unknown>>).map((entry) => {
        const stripped: Record<string, unknown> = { id: entry.id };
        if (entry.priority !== undefined) stripped.priority = entry.priority;
        if (entry.showWhen !== undefined) stripped.showWhen = entry.showWhen;
        if (entry.defaultProps !== undefined) stripped.defaultProps = entry.defaultProps;
        return stripped;
      });
    }
    manifest.slots = slotsOut;
  }

  if (def.i18n) {
    manifest.i18nLangs = Object.keys(def.i18n);
  }

  for (const key of Object.keys(manifest)) {
    if (manifest[key] === undefined) delete manifest[key];
  }

  return manifest;
}
